default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: WDQDMFF-HPC87490
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: USERADMIN
      database: analytics
      warehouse: transforming
      schema: dbt_fanimals
      threads: 6
      client_session_keep_alive: false